# Generated by Django 3.2.10 on 2022-01-05 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_machineids_machine_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineids',
            name='expire',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
