# Generated by Django 3.2.10 on 2022-01-05 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_machineids_expire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineids',
            name='expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
