# Generated by Django 3.2.10 on 2022-01-05 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_machineids_expire'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineIds',
            new_name='Subscription',
        ),
    ]
