# Generated by Django 3.2.10 on 2022-01-05 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220105_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='leads_orderd',
        ),
    ]
