# Generated by Django 3.2.10 on 2022-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_subscription_leads_orderd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='leads_orderd_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
